# Generated by Django 6.0.2 on 2026-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0003_amenity_lodge_lodgeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude (filled by verification team)', null=True),
        ),
        migrations.AddField(
            model_name='lodge',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude (filled by verification team)', null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='location',
            field=models.CharField(help_text='e.g. Akanu, Ozizza, Backgate, etc.', max_length=200),
        ),
    ]
