# Generated by Django 6.0.2 on 2026-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_lodge_latitude_lodge_longitude_alter_lodge_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='rooms_available',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms currently available'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='total_rooms',
            field=models.PositiveIntegerField(default=1, help_text='Total number of rooms in the lodge'),
        ),
    ]
