# Generated by Django 6.0.2 on 2026-07-08 12:34

from django.db import migrations

def seed_amenities(apps, schema_editor):
    Amenity = apps.get_model('lodge', 'Amenity')
    default_amenities = [
        "Running Water",
        "Electricity / Generator",
        "Security Guard",
        "Fully Fenced",
        "Prepaid Meter",
        "Wardrobe",
        "Tiled Floors",
        "Balcony",
        "Kitchen Cabinets"
    ]
    for amenity_name in default_amenities:
        Amenity.objects.get_or_create(name=amenity_name)

def reverse_seed_amenities(apps, schema_editor):
    Amenity = apps.get_model('lodge', 'Amenity')
    Amenity.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0005_lodge_rooms_available_lodge_total_rooms'),
    ]

    operations = [
        migrations.RunPython(seed_amenities, reverse_seed_amenities),
    ]
