# Generated by Django 6.0.2 on 2026-08-23 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0006_seed_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Room 1, Room A, Self-Contain Unit 2', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Describe what's inside the room")),
                ('is_available', models.BooleanField(default=True, help_text='Is this room currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lodge.lodge')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodge.room')),
            ],
        ),
    ]
