# Generated by Django 6.0.2 on 2026-08-23 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0007_room_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='distance_to_campus',
            field=models.CharField(blank=True, default='5 mins walk from Backgate', help_text='e.g. 7 mins walk from Backgate, 5 mins drive from Main Gate', max_length=150),
        ),
        migrations.AddField(
            model_name='lodge',
            name='highlight_tags',
            field=models.CharField(blank=True, default='⚡ 24/7 Power, 💧 Borehole Water, 🛡️ Fenced Compound', help_text='Comma-separated highlight tags (e.g. ⚡ 24/7 Power, 💧 Borehole Water, 🛡️ Fenced Compound)', max_length=255),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars for security')),
                ('water_rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars for water supply')),
                ('light_rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5 stars for power/light supply')),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback from student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lodge.lodge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='lodge.lodge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lodge')},
            },
        ),
    ]
