# Generated by Django 6.0.2 on 2026-08-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0008_lodge_distance_to_campus_lodge_highlight_tags_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='agreement_fee',
            field=models.DecimalField(decimal_places=2, default=15000, help_text='Agreement & Legal commission fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='caution_fee',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Refundable caution deposit', max_digits=10),
        ),
        migrations.AddField(
            model_name='lodge',
            name='inspection_report_notes',
            field=models.TextField(blank=True, default='Inspected by LodgeFinder Agents. Verified road access, functioning borehole, secure compound gate, and good light transformer supply.', help_text='Official inspection summary notes'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='inspection_score',
            field=models.PositiveSmallIntegerField(default=95, help_text='Overall inspection score (0 to 100)'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='is_physically_inspected',
            field=models.BooleanField(default=True, help_text='Physically inspected by LodgeFinder team'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='keke_fare',
            field=models.CharField(blank=True, default='₦100 Keke fare to Main Gate', help_text='e.g. ₦100 Keke fare to Main Gate or 🚶 5 mins walk', max_length=150),
        ),
        migrations.AddField(
            model_name='lodge',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Annual service charge (cleaning, waste)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='price_per_year',
            field=models.DecimalField(decimal_places=2, help_text='Base rent per year', max_digits=10),
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Location keyword (e.g. Backgate)', max_length=100)),
                ('room_type', models.CharField(blank=True, choices=[('', 'Any Room Type'), ('single', 'Single Room'), ('self_contain', 'Self-Contain'), ('flat', 'Flat')], max_length=50)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Looking for 200L Male Roommate at Backgate', max_length=200)),
                ('location_preference', models.CharField(help_text='e.g. Backgate, Ozizza, Frontgate', max_length=150)),
                ('budget_per_year', models.DecimalField(decimal_places=2, help_text='Budget contribution (e.g. 100000)', max_digits=10)),
                ('gender_preference', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'Any Gender')], default='any', max_length=20)),
                ('department_level', models.CharField(help_text='e.g. Computer Science, 300 Level', max_length=100)),
                ('contact_phone', models.CharField(help_text='Phone/WhatsApp number for interested roommates', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Habits, rules, study preferences, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(blank=True, help_text='Optional link to specific lodge', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_requests', to='lodge.lodge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
