# Generated by Django 6.0.2 on 2026-08-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0010_post_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_name',
            field=models.CharField(blank=True, help_text='Agency Name for Verified Agents (e.g. Afikpo Prime Housing)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('owner', 'Lodge Owner'), ('agent', 'Verified House Agent')], default='student', max_length=10),
        ),
    ]
