# Generated by Django 6.0.1 on 2026-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name (e.g., Cornelius Okoro)', max_length=150),
        ),
    ]
