# Generated by Django 6.0.1 on 2026-01-23 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='e.g. Akanu / Campus Gate', max_length=200)),
                ('price_per_year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('self_contain', 'Self-Contain'), ('flat', 'Flat')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, to='lodge.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LodgeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lodges/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lodge.lodge')),
            ],
        ),
    ]
